version: '3'

services:
  message-reader:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env

  mysql:
    image: mysql:latestdocker
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 3
    ports:
      - "3307:3306"
    env_file:
      - .env

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
    env_file:
      - .env
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    volumes:
      - kafka-data:/var/lib/kafka/data
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    env_file:
      - .env

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "8090:8080"
    env_file:
      - .env

volumes:
  zookeeper-data:
  kafka-data:
